howto/config/routes.rb
Rails.application.routes.draw do
  post 'user_token' => 'user_token#create'
  post 'find_user' => 'users#find'
  resources :exercises
  resources :opinions, only: [:index, :show]
  resources :oral_args, only: [:index, :show]
  resources :lesson_vital_facts, only: [:index, :show]
  resources :lesson_opinions, only: [:index, :show]
  resources :lesson_oral_arguments, only: [:index, :show]
  resources :lesson_texts, only: [:index, :show]
  resources :vital_infos, only: [:index, :show]
  resources :lessons, only: [:index, :show]
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

howto/app/models/oral_arg.rb
class OralArg < ApplicationRecord
  belongs_to :lesson
end

howto/app/controllers/oral_args_controller.rb
class OralArgsController < ApplicationController
  before_action :set_oral_arg, only: [:show, :edit, :update, :destroy]
  

  # GET /oral_args
  # GET /oral_args.json
  def index
    render json: OralArg.all
  end

  # GET /oral_args/1
  # GET /oral_args/1.json
  def show
    render json: OralArg.find(params[:id])
  end

  # GET /oral_args/new
  def new
    @oral_arg = OralArg.new
  end

  # GET /oral_args/1/edit
  def edit
  end

  # POST /oral_args
  # POST /oral_args.json
  def create
    @oral_arg = OralArg.new(oral_arg_params)

    respond_to do |format|
      if @oral_arg.save
        format.html { redirect_to @oral_arg, notice: 'Oral arg was successfully created.' }
        format.json { render :show, status: :created, location: @oral_arg }
      else
        format.html { render :new }
        format.json { render json: @oral_arg.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /oral_args/1
  # PATCH/PUT /oral_args/1.json
  def update
    respond_to do |format|
      if @oral_arg.update(oral_arg_params)
        format.html { redirect_to @oral_arg, notice: 'Oral arg was successfully updated.' }
        format.json { render :show, status: :ok, location: @oral_arg }
      else
        format.html { render :edit }
        format.json { render json: @oral_arg.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /oral_args/1
  # DELETE /oral_args/1.json
  def destroy
    @oral_arg.destroy
    respond_to do |format|
      format.html { redirect_to oral_args_url, notice: 'Oral arg was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_oral_arg
      @oral_arg = OralArg.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def oral_arg_params
      params.require(:oral_arg).permit(:link_url, :header_text, :desc_text)
    end
end

howto/app/helpers/oral_args_helper.rb
module OralArgsHelper
end

howto/app/views/oral_args/_form.html.erb
<%= form_with(model: oral_arg, local: true) do |form| %>
  <% if oral_arg.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(oral_arg.errors.count, "error") %> prohibited this oral_arg from being saved:</h2>

      <ul>
      <% oral_arg.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :link_url %>
    <%= form.text_field :link_url %>
  </div>

  <div class="field">
    <%= form.label :header_text %>
    <%= form.text_field :header_text %>
  </div>

  <div class="field">
    <%= form.label :desc_text %>
    <%= form.text_field :desc_text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

howto/app/views/oral_args/edit.html.erb
<h1>Editing Oral Arg</h1>

<%= render 'form', oral_arg: @oral_arg %>

<%= link_to 'Show', @oral_arg %> |
<%= link_to 'Back', oral_args_path %>

howto/app/views/oral_args/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Oral Args</h1>

<table>
  <thead>
    <tr>
      <th>Link url</th>
      <th>Header text</th>
      <th>Desc text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @oral_args.each do |oral_arg| %>
      <tr>
        <td><%= oral_arg.link_url %></td>
        <td><%= oral_arg.header_text %></td>
        <td><%= oral_arg.desc_text %></td>
        <td><%= link_to 'Show', oral_arg %></td>
        <td><%= link_to 'Edit', edit_oral_arg_path(oral_arg) %></td>
        <td><%= link_to 'Destroy', oral_arg, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Oral Arg', new_oral_arg_path %>

howto/app/views/oral_args/new.html.erb
<h1>New Oral Arg</h1>

<%= render 'form', oral_arg: @oral_arg %>

<%= link_to 'Back', oral_args_path %>

howto/app/views/oral_args/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link url:</strong>
  <%= @oral_arg.link_url %>
</p>

<p>
  <strong>Header text:</strong>
  <%= @oral_arg.header_text %>
</p>

<p>
  <strong>Desc text:</strong>
  <%= @oral_arg.desc_text %>
</p>

<%= link_to 'Edit', edit_oral_arg_path(@oral_arg) %> |
<%= link_to 'Back', oral_args_path %>