howto/config/routes.rb
Rails.application.routes.draw do
  post 'user_token' => 'user_token#create'
  post 'find_user' => 'users#find'
  resources :exercises
  resources :opinions, only: [:index, :show]
  resources :oral_args, only: [:index, :show]
  resources :lesson_vital_facts, only: [:index, :show]
  resources :lesson_opinions, only: [:index, :show]
  resources :lesson_oral_arguments, only: [:index, :show]
  resources :lesson_texts, only: [:index, :show]
  resources :vital_infos, only: [:index, :show]
  resources :lessons, only: [:index, :show]
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

howto/app/models/lesson_text.rb
class LessonText < ApplicationRecord
  belongs_to :lesson
end

howto/app/controllers/lesson_texts_controller.rb
class LessonTextsController < ApplicationController
  before_action :set_lesson_text, only: [:show, :edit, :update, :destroy]
  

  # GET /lesson_texts
  # GET /lesson_texts.json
  def index
    render json: LessonText.all
  end

  # GET /lesson_texts/1
  # GET /lesson_texts/1.json
  def show
    render json: LessonText.find(params[:id])
  end

  # GET /lesson_texts/new
  def new
    @lesson_text = LessonText.new
  end

  # GET /lesson_texts/1/edit
  def edit
  end

  # POST /lesson_texts
  # POST /lesson_texts.json
  def create
    @lesson_text = LessonText.new(lesson_text_params)

    respond_to do |format|
      if @lesson_text.save
        format.html { redirect_to @lesson_text, notice: 'Lesson text was successfully created.' }
        format.json { render :show, status: :created, location: @lesson_text }
      else
        format.html { render :new }
        format.json { render json: @lesson_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lesson_texts/1
  # PATCH/PUT /lesson_texts/1.json
  def update
    respond_to do |format|
      if @lesson_text.update(lesson_text_params)
        format.html { redirect_to @lesson_text, notice: 'Lesson text was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson_text }
      else
        format.html { render :edit }
        format.json { render json: @lesson_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lesson_texts/1
  # DELETE /lesson_texts/1.json
  def destroy
    @lesson_text.destroy
    respond_to do |format|
      format.html { redirect_to lesson_texts_url, notice: 'Lesson text was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson_text
      @lesson_text = LessonText.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_text_params
      params.require(:lesson_text).permit(:adv, :int, :sim)
    end
end

howto/app/helpers/lesson_texts_helper.rb
module LessonTextsHelper
end

howto/app/views/lesson_texts/_form.html.erb
<%= form_with(model: lesson_text, local: true) do |form| %>
  <% if lesson_text.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lesson_text.errors.count, "error") %> prohibited this lesson_text from being saved:</h2>

      <ul>
      <% lesson_text.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :adv %>
    <%= form.text_field :adv %>
  </div>

  <div class="field">
    <%= form.label :int %>
    <%= form.text_field :int %>
  </div>

  <div class="field">
    <%= form.label :sim %>
    <%= form.text_field :sim %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

howto/app/views/lesson_texts/edit.html.erb
<h1>Editing Lesson Text</h1>

<%= render 'form', lesson_text: @lesson_text %>

<%= link_to 'Show', @lesson_text %> |
<%= link_to 'Back', lesson_texts_path %>

howto/app/views/lesson_texts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lesson Texts</h1>

<table>
  <thead>
    <tr>
      <th>Adv</th>
      <th>Int</th>
      <th>Sim</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lesson_texts.each do |lesson_text| %>
      <tr>
        <td><%= lesson_text.adv %></td>
        <td><%= lesson_text.int %></td>
        <td><%= lesson_text.sim %></td>
        <td><%= link_to 'Show', lesson_text %></td>
        <td><%= link_to 'Edit', edit_lesson_text_path(lesson_text) %></td>
        <td><%= link_to 'Destroy', lesson_text, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lesson Text', new_lesson_text_path %>

howto/app/views/lesson_texts/new.html.erb
<h1>New Lesson Text</h1>

<%= render 'form', lesson_text: @lesson_text %>

<%= link_to 'Back', lesson_texts_path %>

howto/app/views/lesson_texts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Adv:</strong>
  <%= @lesson_text.adv %>
</p>

<p>
  <strong>Int:</strong>
  <%= @lesson_text.int %>
</p>

<p>
  <strong>Sim:</strong>
  <%= @lesson_text.sim %>
</p>

<%= link_to 'Edit', edit_lesson_text_path(@lesson_text) %> |
<%= link_to 'Back', lesson_texts_path %>