howto/config/routes.rb
Rails.application.routes.draw do
  post 'user_token' => 'user_token#create'
  post 'find_user' => 'users#find'
  resources :exercises
  resources :opinions, only: [:index, :show]
  resources :oral_args, only: [:index, :show]
  resources :lesson_vital_facts, only: [:index, :show]
  resources :lesson_opinions, only: [:index, :show]
  resources :lesson_oral_arguments, only: [:index, :show]
  resources :lesson_texts, only: [:index, :show]
  resources :vital_infos, only: [:index, :show]
  resources :lessons, only: [:index, :show]
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

howto/app/models/opinion.rb
class Opinion < ApplicationRecord
  belongs_to :lesson
end

howto/app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  before_action :set_opinion, only: [:show, :edit, :update, :destroy]
  

  # GET /opinions
  # GET /opinions.json
  def index
    render json: Opinion.all
  end

  # GET /opinions/1
  # GET /opinions/1.json
  def show
    render json: Opinion.find(params[:id])
  end

  # GET /opinions/new
  def new
    @opinion = Opinion.new
  end

  # GET /opinions/1/edit
  def edit
  end

  # POST /opinions
  # POST /opinions.json
  def create
    @opinion = Opinion.new(opinion_params)

    respond_to do |format|
      if @opinion.save
        format.html { redirect_to @opinion, notice: 'Opinion was successfully created.' }
        format.json { render :show, status: :created, location: @opinion }
      else
        format.html { render :new }
        format.json { render json: @opinion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /opinions/1
  # PATCH/PUT /opinions/1.json
  def update
    respond_to do |format|
      if @opinion.update(opinion_params)
        format.html { redirect_to @opinion, notice: 'Opinion was successfully updated.' }
        format.json { render :show, status: :ok, location: @opinion }
      else
        format.html { render :edit }
        format.json { render json: @opinion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /opinions/1
  # DELETE /opinions/1.json
  def destroy
    @opinion.destroy
    respond_to do |format|
      format.html { redirect_to opinions_url, notice: 'Opinion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_opinion
      @opinion = Opinion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def opinion_params
      params.require(:opinion).permit(:link_url, :header_text, :desc_text)
    end
end

howto/app/helpers/opinions_helper.rb
module OpinionsHelper
end

howto/app/views/opinions/_form.html.erb
<%= form_with(model: opinion, local: true) do |form| %>
  <% if opinion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(opinion.errors.count, "error") %> prohibited this opinion from being saved:</h2>

      <ul>
      <% opinion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :link_url %>
    <%= form.text_field :link_url %>
  </div>

  <div class="field">
    <%= form.label :header_text %>
    <%= form.text_field :header_text %>
  </div>

  <div class="field">
    <%= form.label :desc_text %>
    <%= form.text_field :desc_text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

howto/app/views/opinions/edit.html.erb
<h1>Editing Opinion</h1>

<%= render 'form', opinion: @opinion %>

<%= link_to 'Show', @opinion %> |
<%= link_to 'Back', opinions_path %>

howto/app/views/opinions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Opinions</h1>

<table>
  <thead>
    <tr>
      <th>Link url</th>
      <th>Header text</th>
      <th>Desc text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @opinions.each do |opinion| %>
      <tr>
        <td><%= opinion.link_url %></td>
        <td><%= opinion.header_text %></td>
        <td><%= opinion.desc_text %></td>
        <td><%= link_to 'Show', opinion %></td>
        <td><%= link_to 'Edit', edit_opinion_path(opinion) %></td>
        <td><%= link_to 'Destroy', opinion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Opinion', new_opinion_path %>

howto/app/views/opinions/new.html.erb
<h1>New Opinion</h1>

<%= render 'form', opinion: @opinion %>

<%= link_to 'Back', opinions_path %>

howto/app/views/opinions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link url:</strong>
  <%= @opinion.link_url %>
</p>

<p>
  <strong>Header text:</strong>
  <%= @opinion.header_text %>
</p>

<p>
  <strong>Desc text:</strong>
  <%= @opinion.desc_text %>
</p>

<%= link_to 'Edit', edit_opinion_path(@opinion) %> |
<%= link_to 'Back', opinions_path %>