howto/config/routes.rb
Rails.application.routes.draw do
  post 'user_token' => 'user_token#create'
  post 'find_user' => 'users#find'
  resources :exercises
  resources :opinions, only: [:index, :show]
  resources :oral_args, only: [:index, :show]
  resources :lesson_vital_facts, only: [:index, :show]
  resources :lesson_opinions, only: [:index, :show]
  resources :lesson_oral_arguments, only: [:index, :show]
  resources :lesson_texts, only: [:index, :show]
  resources :vital_infos, only: [:index, :show]
  resources :lessons, only: [:index, :show]
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

howto/app/helpers/vital_info_helper.rb
module VitalInfoHelper
end

howto/app/helpers/vital_infos_helper.rb
module VitalInfosHelper
end

howto/app/views/vital_infos/_form.html.erb
<%= form_with(model: vital_info, local: true) do |form| %>
  <% if vital_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vital_info.errors.count, "error") %> prohibited this vital_info from being saved:</h2>

      <ul>
      <% vital_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

howto/app/views/vital_infos/edit.html.erb
<h1>Editing Vital Info</h1>

<%= render 'form', vital_info: @vital_info %>

<%= link_to 'Show', @vital_info %> |
<%= link_to 'Back', vital_infos_path %>

howto/app/views/vital_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vital Infos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vital_infos.each do |vital_info| %>
      <tr>
        <td><%= link_to 'Show', vital_info %></td>
        <td><%= link_to 'Edit', edit_vital_info_path(vital_info) %></td>
        <td><%= link_to 'Destroy', vital_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vital Info', new_vital_info_path %>

howto/app/views/vital_infos/new.html.erb
<h1>New Vital Info</h1>

<%= render 'form', vital_info: @vital_info %>

<%= link_to 'Back', vital_infos_path %>

howto/app/views/vital_infos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_vital_info_path(@vital_info) %> |
<%= link_to 'Back', vital_infos_path %>